baseurl = "http://rockn-go.herokuapp.com/"
languageCode = "de-de"
title = "Rockn`go"
theme = "hugoscroll"
[params]
github = "rocknrollmarc"
description = "Ruby on rails / Go / NodeJS / Agile coach / full stack freelancer situated in Hamburg Germany"
twitter = "bluemner"
